apiVersion: v3
appVersion: 3.0.0-alpha1
description: A Helm chart for ioFog services
name: iofog
version: 3.0.0-alpha1
keywords:
  - iofog
home: https://iofog.org/
sources:
  - https://github.com/eclipse-iofog/helm
