defaultNamespace: "iofog"

createCustomResource: true

controller:
  replicas: 1
  image: "gcr.io/focal-freedom-236620/controller:develop"
  imagePullPolicy: Always
  host: controller
  port: 51121
  loadBalancerIP: ""

connector:
  replicas: 1
  image: "gcr.io/focal-freedom-236620/connector:develop"
  imagePullPolicy: Always
  port: 8080

operator:
  replicas: 1
  image: "gcr.io/focal-freedom-236620/operator:develop"
  imagePullPolicy: Always
  port: 60000

kubelet:
  replicas: 1
  image: "gcr.io/focal-freedom-236620/kubelet:develop"
  imagePullPolicy: Always
  apiServerHost: kubernetes.default.svc
  apiServerPort: 443

test:
  credentials: ""
