namespace: iofog

controller:
  replicas: 1
  image: "iofog/controller:dev"
  imagePullPolicy: Always
  token: "INVALID_TOKEN"
  host: http://controller
  port: 51121
  targetPort: 54421

connector:
  replicas: 1
  image: "iofog/connector:dev"
  imagePullPolicy: Always
  port: 8080

scheduler:
  replicas: 1
  image: "iofog/iofog-scheduler:develop"
  imagePullPolicy: Always

operator:
  replicas: 1
  image: "iofog/iofog-operator:develop"
  imagePullPolicy: Always
  port: 60000

kubelet:
  replicas: 1
  image: "iofog/iofog-kubelet:develop"
  imagePullPolicy: Always
  apiServerHost: kubernetes.default.svc
  apiServerPort: 443
