defaultNamespace: "default"

createCustomResources: true

controlPlane:
  user:
    firstName: "First"
    surname: "Second"
    email: "user@domain.com"
    password: "H23fkidf9hoibf2nlk"
  database:
    provider: ""
    host: ""
    port: 0
    password: ""
    dbName: ""
  controller:
    replicas: 1
    image: "gcr.io/focal-freedom-236620/controller:2.0.0-beta"
    imagePullPolicy: Always
  kubeletImage: "gcr.io/focal-freedom-236620/kubelet:2.0.0-beta"
  proxyImage: "iofog/proxy:2.0.0-beta"
  routerImage: "iofog/router:2.0.0-beta"
  portManagerImage: "gcr.io/focal-freedom-236620/port-manager:2.0.0-beta"
  loadBalancerIp: ""
  serviceType: "LoadBalancer"

operator:
  replicas: 1
  image: "gcr.io/focal-freedom-236620/operator:2.0.0-beta"
  imagePullPolicy: Always
