defaultNamespace: "iofog"

createCustomResource: true

controller:
  replicas: 1
  image: "iofog/controller:1.2.0"
  imagePullPolicy: Always
  host: controller
  port: 51121
  loadBalancerIP: ""

connector:
  replicas: 1
  image: "iofog/connector:1.2.0"
  imagePullPolicy: Always
  port: 8080

operator:
  replicas: 1
  image: "iofog/iofog-operator:1.2.0"
  imagePullPolicy: Always
  port: 60000

kubelet:
  replicas: 1
  image: "iofog/iofog-kubelet:1.2.0"
  imagePullPolicy: Always
  apiServerHost: kubernetes.default.svc
  apiServerPort: 443

tests:
  image: "iofog/test-runner:1.2.0"
  imagePullPolicy: Always
