defaultNamespace: "default"

createCustomResources: true

controlPlane:
  user:
    firstName: "First"
    surname: "Second"
    email: "user@domain.com"
    password: "H23fkidf9hoibf2nlk"
  database:
    provider: ""
    host: ""
    port: 0
    password: ""
    dbName: ""
  controller:
    replicas: 1
    image: "iofog/controller:2.0.0-rc1"
    imagePullPolicy: Always
  kubeletImage: "iofog/iofog-kubelet:2.0.0-rc1"
  proxyImage: "iofog/proxy:2.0.0-rc1"
  routerImage: "iofog/router:2.0.0-rc1"
  portManagerImage: "iofog/port-manager:2.0.0-rc1"

operator:
  replicas: 1
  image: "iofog/operator:2.0.0-rc1"
  imagePullPolicy: Always
