defaultNamespace: "default"

createCustomResources: true

controlPlane:
  user:
    firstName: "First"
    surname: "Second"
    email: "user@domain.com"
    password: "H23fkidf9hoibf2nlk"
  database:
    provider: ""
    host: ""
    port: 0
    password: ""
    dbName: ""
  controller:
    replicas: 1
    image: "iofog/controller:1.3.1"
    imagePullPolicy: Always
  kubeletImage: "iofog/iofog-kubelet:1.3.0"
  loadBalancerIp: ""
  serviceType: "LoadBalancer"

connectors:
  image: "iofog/connector:1.3.0"
  serviceType: "LoadBalancer"
  instanceNames:
    - "first"
    - "second"

operator:
  replicas: 1
  image: "iofog/iofog-operator:1.3.0"
  imagePullPolicy: Always
