defaultNamespace: "default"

createCustomResources: true

controlPlane:
  user:
    firstName: "First"
    surname: "Second"
    email: "user@domain.com"
    password: "H23fkidf9hoibf2nlk"
  database:
    provider: ""
    host: ""
    port: 0
    password: ""
    dbName: ""
  controller:
    replicas: 1
    image: "gcr.io/focal-freedom-236620/controller:develop"
    imagePullPolicy: Always
  kubeletImage: "gcr.io/focal-freedom-236620/kubelet:develop"
  loadBalancerIP: ""
  serviceType: "LoadBalancer"

connectors:
  image: "gcr.io/focal-freedom-236620/connector:develop"
  instanceNames:
    - "first"
    - "second"

operator:
  replicas: 1
  image: "gcr.io/focal-freedom-236620/operator:develop"
  imagePullPolicy: Always