defaultNamespace: "default"

createCustomResources: true

controlPlane:
  user:
    firstName: "First"
    surname: "Second"
    email: "user@domain.com"
    password: "H23fkidf9hoibf2nlk"
  database:
    provider: ""
    host: ""
    port: 0
    password: ""
    dbName: ""
  images:
    pullSecret: ""
    controller: "gcr.io/focal-freedom-236620/controller:develop"
    router: "gcr.io/focal-freedom-236620/router:develop"
    portManager: "gcr.io/focal-freedom-236620/port-manager:develop"
    proxy: "gcr.io/focal-freedom-236620/proxy:develop"
    imagePullPolicy: Always
  replicas:
    controller: 1
  services:
    controller:
      type: "LoadBalancer"
    router:
      type: "LoadBalancer"
    proxy:
      type: "LoadBalancer"

operator:
  replicas: 1
  image: "gcr.io/focal-freedom-236620/operator:develop"
  imagePullPolicy: Always
