namespace: iofog


controller:
  token: ""
  host: http://controller
  port: 51121


scheduler:
  replicas: 1
  image: "iofog/iofog-scheduler:develop"
  imagePullPolicy: Always

operator:
  replicas: 1
  image: "iofog/iofog-operator:develop"
  imagePullPolicy: Always
  port: 60000

kubelet:
  replicas: 1
  image: "iofog/iofog-kubelet:develop"
  imagePullPolicy: Always
  apiServerHost: kubernetes.default.svc
  apiServerPort: 443