apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
  namespace: {{ .Values.namespace }}
  labels:
    name: connector
spec:
  replicas: {{ .Values.connector.replicas }}
  selector:
    matchLabels:
      name: connector
  template:
    metadata:
      labels:
        name: connector
    spec:
      initContainers:
        - name: wait-for-controller
          image: fmiguelez/alpine-curl-jq:latest
          env:
            - name: CONTROLLER_URL
              value: "{{ .Values.controller.host }}:{{ .Values.controller.port }}/api/v3"
          command: ['sh', '-c', 'until [[ $(curl ${CONTROLLER_URL}/status 2>/dev/null | jq -r ".status") == "online" ]]; do echo "Waiting for Controller..."; sleep 5; done']
        - name: wait-for-connector-ip
          image: bitnami/kubectl:latest
          command: ['sh', '-c', 'kubectl help; tail -f /dev/null']
      containers:
      - name: connector
        image: {{ .Values.connector.image }}
        imagePullPolicy: {{ .Values.connector.imagePullPolicy }}
---
kind: Service
apiVersion: v1
metadata:
  name: connector
  namespace: {{ .Values.namespace }}
  labels:
    name: connector
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.connector.port }}
      targetPort: {{ .Values.connector.port }}
      protocol: TCP
  selector:
    name: connector
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-role-svc-info
subjects:
  - kind: ServiceAccount
    name: k8s-role-svc-info
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-role-svc-info
