apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
  namespace: {{ .Values.namespace }}
  labels:
    name: connector
spec:
  replicas: {{ .Values.connector.replicas }}
  selector:
    matchLabels:
      name: connector
  template:
    metadata:
      labels:
        name: connector
    spec:
      containers:
      - name: connector
        image: {{ .Values.connector.image }}
        imagePullPolicy: {{ .Values.connector.imagePullPolicy }}
---
kind: Service
apiVersion: v1
metadata:
  name: connector
  namespace: {{ .Values.namespace }}
  labels:
    name: connector
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.connector.port }}
      targetPort: {{ .Values.connector.port }}
      protocol: TCP
  selector:
    name: connector