apiVersion: iofog.org/v2
kind: ControlPlane
metadata:
  name: iokog
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
spec:
  database:
    provider: {{ .Values.database.provider }}
    host: {{ .Values.database.host }}
    port: {{ .Values.database.port }}
    user: {{ .Values.database.user }}
    password: {{ .Values.database.password }}
    databaseName: {{ .Values.database.dbName }}
  images:
    controller: {{ .Values.images.controller }}
    kubelet: {{ .Values.images.kubelet }}
    portManager: {{ .Values.images.portManager }}
    proxy: {{ .Values.images.proxy }}
    router: {{ .Values.images.router }}
  replicas:
    controller: {{ .Values.replicas.controller }}
  services:
    controller:
      type: LoadBalancer
    proxy:
      type: LoadBalancer
    router:
      type: LoadBalancer
  user:
    name: {{ .Values.user.firstName }}
    surname: {{ .Values.user.surname }}
    email: {{ .Values.user.email }}
    password: {{ .Values.user.password | b64enc }}
