{{ if .Values.createCustomResources }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kogs.iofog.org
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: iofog.org
  names:
    kind: Kog
    listKind: KogList
    plural: kogs
    singular: kog
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.iofog.org
  namespace: {{ .Release.Namespace | default .Values.defaultNamespace }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: iofog.org
  names:
    kind: Application
    listKind: ApplicationList
    plural: apps
    singular: app
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
{{ end }}
