apiVersion: v1
kind: ServiceAccount
metadata:
  name: iofog-kubelet
  namespace: {{ .Values.namespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iofog-kubelet
subjects:
  - kind: ServiceAccount
    name: iofog-kubelet
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelet
  namespace: {{ .Values.namespace }}
  labels:
    name: kubelet
spec:
  replicas: {{ .Values.kubelet.replicas }}
  selector:
    matchLabels:
      name: kubelet
  template:
    metadata:
      labels:
        name: kubelet
    spec:
      serviceAccountName: iofog-kubelet
      initContainers:
        - name: wait-for-controller
          image: fmiguelez/alpine-curl-jq:latest
          env:
            - name: CONTROLLER_URL
              value: "{{ .Values.controller.host }}:{{ .Values.controller.port }}/api/v3"
          command: ['sh', '-c', 'until [[ $(curl ${CONTROLLER_URL}/status 2>/dev/null | jq -r ".status") == "online" ]]; do echo "Waiting for Controller..."; sleep 5; done']
      containers:
      - name: kubelet
        image: {{ .Values.kubelet.image }}
        imagePullPolicy: {{ .Values.kubelet.imagePullPolicy }}
        args: 
        - "--namespace"
        - {{ .Values.namespace }}
        - "--iofog-token"
        - {{ .Values.controller.token | quote }}
        - "--iofog-url"
        - {{ .Values.controller.host }}:{{ .Values.controller.port }}
