apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kogs.iofog.org
spec:
  group: iofog.org
  names:
    kind: Kog
    listKind: KogList
    plural: kogs
    singular: kog
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v2
    served: true
    storage: true
  - name: v1
    served: true
    storage: false
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.iofog.org
spec:
  group: iofog.org
  names:
    kind: Application
    listKind: ApplicationList
    plural: apps
    singular: app
  scope: namespaced
  subresources:
    status: {}
  versions:
  - name: v2
    served: true
    storage: true
  - name: v1
    served: true
    storage: false
